version: "3.8"

services:

  db:
    image: mysql:8.0
    container_name: bank_import_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_import
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33060:3306"

volumes:
  db_data: